# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SproutMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SproutMobile

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'

  target 'SproutMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SproutMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end